services:
  - type: web
    name: trackilo
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm run setup-production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_LIFETIME
        value: 1d
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DEPLOYMENT_URL
        value: https://trackilo.onrender.com
    healthCheckPath: /api/v1/auth/check-status
    autoDeploy: true 